apiVersion: v1
kind: Service
metadata:
  name: forge-api
spec:
  type: {{ .Values.service.type }}
  selector:
    app: forge-api
  ports:
    - port: {{ .Values.service.apiPort }}
      targetPort: {{ .Values.service.apiPort }}
      name: http
