apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack-enterprise-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slack-enterprise-bot
  template:
    metadata:
      labels:
        app: slack-enterprise-bot
    spec:
      containers:
        - name: slack-bot
          image: "{{ .Values.registry }}/slack-enterprise-bot:{{ .Values.tag }}"
          imagePullPolicy: {{ .Values.pullPolicy }}
          env:
            - name: LICENSE_KEY
              value: "{{ .Values.global.licenseKey }}"
            - name: DATABASE_URL
              value: "{{ .Values.global.env.DATABASE_URL }}"
