global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: server
    static_configs:
      - targets: ['server:4000']
    metrics_path: /metrics

  - job_name: ingestor
    static_configs:
      - targets: ['ingestor:9302']

  - job_name: slack-bot
    static_configs:
      - targets: ['slack-bot:9301']

  - job_name: forge
    static_configs:
      - targets: ['forge:9304']
    metrics_path: /metrics
    scheme: http

  - job_name: nginx
    static_configs:
      - targets: ['nginx:9113']

  - job_name: loki
    static_configs:
      - targets: ['loki:3100']
