apiVersion: apps/v1
kind: Deployment
metadata:
  name: forge-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forge-nginx
  template:
    metadata:
      labels:
        app: forge-nginx
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.nginx.image }}"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: forge-nginx
spec:
  type: {{ .Values.service.type }}
  selector:
    app: forge-nginx
  ports:
    - port: 80
      targetPort: 80
